steps:
  - label: "Build FlashMLA wheel - CUDA 12.9 (x86_64)"
    depends_on: ~
    agents:
      queue: cpu_queue_postmerge
    commands:
      - "DOCKER_BUILDKIT=1 docker build --build-arg CUDA_VERSION=12.9.1 --build-arg TORCH_CUDA_ARCH_LIST='9.0' --build-arg PYTORCH_INDEX_URL=https://download.pytorch.org/whl/cu129 --build-arg SCCACHE_BUCKET=lexiq-nova-build-sccache --build-arg SCCACHE_REGION=us-west-2 --tag flashmla-build:cu129 --target build -f .buildkite/Dockerfile ."
      - "mkdir -p artifacts"
      - "docker run --rm -v $(pwd)/artifacts:/artifacts_host flashmla-build:cu129 bash -c 'cp -r dist /artifacts_host && chmod -R a+rw /artifacts_host'"
      - "pip install modal"
      - "export MODAL_TOKEN_ID=$(buildkite-agent secret get MODAL_TOKEN_ID)"
      - "export MODAL_TOKEN_SECRET=$(buildkite-agent secret get MODAL_TOKEN_SECRET)"
      - "modal token set --token-id \"$${MODAL_TOKEN_ID}\" --token-secret \"$${MODAL_TOKEN_SECRET}\" --profile=remodlai"
      - "modal profile activate remodlai"
      - "WHEEL_FILE=$(ls artifacts/dist/*.whl | head -1)"
      - "modal volume put wheels \"$${WHEEL_FILE}\" \"/packages/$(basename \"$${WHEEL_FILE}\")\""
    env:
      DOCKER_BUILDKIT: "1"

  - label: "Build FlashMLA wheel - CUDA 12.8 (x86_64)"
    depends_on: ~
    agents:
      queue: cpu_queue_postmerge
    commands:
      - "DOCKER_BUILDKIT=1 docker build --build-arg CUDA_VERSION=12.8.1 --build-arg TORCH_CUDA_ARCH_LIST='8.0 8.9 9.0' --build-arg PYTORCH_INDEX_URL=https://download.pytorch.org/whl/cu128 --build-arg SCCACHE_BUCKET=lexiq-nova-build-sccache --build-arg SCCACHE_REGION=us-west-2 --build-arg FLASH_MLA_DISABLE_SM100=1 --tag flashmla-build:cu128 --target build -f .buildkite/Dockerfile ."
      - "mkdir -p artifacts"
      - "docker run --rm -v $(pwd)/artifacts:/artifacts_host flashmla-build:cu128 bash -c 'cp -r dist /artifacts_host && chmod -R a+rw /artifacts_host'"
      - "pip install modal"
      - "export MODAL_TOKEN_ID=$(buildkite-agent secret get MODAL_TOKEN_ID)"
      - "export MODAL_TOKEN_SECRET=$(buildkite-agent secret get MODAL_TOKEN_SECRET)"
      - "modal token set --token-id \"$${MODAL_TOKEN_ID}\" --token-secret \"$${MODAL_TOKEN_SECRET}\" --profile=remodlai"
      - "modal profile activate remodlai"
      - "WHEEL_FILE=$(ls artifacts/dist/*.whl | head -1)"
      - "modal volume put wheels \"$${WHEEL_FILE}\" \"/packages/$(basename \"$${WHEEL_FILE}\")\""
    env:
      DOCKER_BUILDKIT: "1"

  - label: "Build FlashMLA wheel - CUDA 12.6 (x86_64)"
    depends_on: ~
    agents:
      queue: cpu_queue_postmerge
    commands:
      - "DOCKER_BUILDKIT=1 docker build --build-arg CUDA_VERSION=12.6.3 --build-arg TORCH_CUDA_ARCH_LIST='8.0 8.9 9.0' --build-arg PYTORCH_INDEX_URL=https://download.pytorch.org/whl/cu126 --build-arg SCCACHE_BUCKET=lexiq-nova-build-sccache --build-arg SCCACHE_REGION=us-west-2 --build-arg FLASH_MLA_DISABLE_SM100=1 --tag flashmla-build:cu126 --target build -f .buildkite/Dockerfile ."
      - "mkdir -p artifacts"
      - "docker run --rm -v $(pwd)/artifacts:/artifacts_host flashmla-build:cu126 bash -c 'cp -r dist /artifacts_host && chmod -R a+rw /artifacts_host'"
      - "pip install modal"
      - "export MODAL_TOKEN_ID=$(buildkite-agent secret get MODAL_TOKEN_ID)"
      - "export MODAL_TOKEN_SECRET=$(buildkite-agent secret get MODAL_TOKEN_SECRET)"
      - "modal token set --token-id \"$${MODAL_TOKEN_ID}\" --token-secret \"$${MODAL_TOKEN_SECRET}\" --profile=remodlai"
      - "modal profile activate remodlai"
      - "WHEEL_FILE=$(ls artifacts/dist/*.whl | head -1)"
      - "modal volume put wheels \"$${WHEEL_FILE}\" \"/packages/$(basename \"$${WHEEL_FILE}\")\""
    env:
      DOCKER_BUILDKIT: "1"

  - label: "Build FlashMLA wheel - CUDA 12.9 (aarch64)"
    depends_on: ~
    agents:
      queue: arm64_cpu_queue_postmerge
    commands:
      - "DOCKER_BUILDKIT=1 docker build --build-arg CUDA_VERSION=12.9.1 --build-arg TORCH_CUDA_ARCH_LIST='8.7 8.9 9.0' --build-arg PYTORCH_INDEX_URL=https://download.pytorch.org/whl/cu129 --build-arg SCCACHE_BUCKET=lexiq-nova-build-sccache --build-arg SCCACHE_REGION=us-west-2 --tag flashmla-build:cu129-aarch64 --target build -f .buildkite/Dockerfile ."
      - "mkdir -p artifacts"
      - "docker run --rm -v $(pwd)/artifacts:/artifacts_host flashmla-build:cu129-aarch64 bash -c 'cp -r dist /artifacts_host && chmod -R a+rw /artifacts_host'"
      - "pip install modal"
      - "export MODAL_TOKEN_ID=$(buildkite-agent secret get MODAL_TOKEN_ID)"
      - "export MODAL_TOKEN_SECRET=$(buildkite-agent secret get MODAL_TOKEN_SECRET)"
      - "modal token set --token-id \"$${MODAL_TOKEN_ID}\" --token-secret \"$${MODAL_TOKEN_SECRET}\" --profile=remodlai"
      - "modal profile activate remodlai"
      - "WHEEL_FILE=$(ls artifacts/dist/*.whl | head -1)"
      - "modal volume put wheels \"$${WHEEL_FILE}\" \"/packages/$(basename \"$${WHEEL_FILE}\")\""
    env:
      DOCKER_BUILDKIT: "1"
# this only allows buildkite to know these secrets exist.  you must use `buildkite-agent secret get` to get the values.
secrets:
  - MODAL_TOKEN_ID
  - MODAL_TOKEN_SECRET

